
CREATE TABLE IF NOT EXISTS "movimentacoes" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_produto" INTEGER NOT NULL,
	"tipo_movimentacao" VARCHAR(12) NOT NULL,
	"quantidade" INTEGER NOT NULL,
	"data_movimentacao" DATE NOT NULL,
	"observacao" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "produtos_movimentacoes" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_produtos" INTEGER NOT NULL,
	"id_movimentacao" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


ALTER TABLE "produtos_movimentacoes"
ADD FOREIGN KEY("id_produtos") REFERENCES "produtos"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "produtos_movimentacoes"
ADD FOREIGN KEY("id_movimentacao") REFERENCES "movimentacoes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;




INSERT INTO produtos (id, nome, categoria, quantidade, valor_unitario)
VALUES
(1, 'Martelo', 'Ferramentas', 30, 29.99),
(2, 'Serrote', 'Ferramentas', 20, 55.99),
(3, 'Lichadeira', 'ferramentas', 10, 199.99),
(4, 'Cloro Ativado', 'Produtos de limpeza', 25, 17.99),
(5, 'Desengraxante liquído', 'Produtos de limpeza', 10, 19.99);


CREATE VIEW vw_estoque AS
SELECT id, nome, quantidade, valor_unitario, quantidade * valor_unitario
FROM produtos;
SELECT * FROM vw_estoque;

select * from movimentacoes;

INSERT INTO movimentacoes (id, id_produto, tipo_movimentacao, quantidade, data_movimentacao, observacao)
VALUES
(2,3, 'Saida', 5, '16/07/2026', 'nada');